#!/usr/bin/env python3
"""
Put the pinned third-party apps (PrebuiltApps/apps.json) into the tree.

For each app: fetch the APK and its licence into the download cache, check
both against the pinned sha256, stage them in vendor/jetson-tv/PrebuiltApps/,
and generate the build modules. Run by tree-local-changes.sh, so by every
build; a cache hit costs nothing and needs no network.

Why it takes three kinds of module rather than one:

- The APK is imported by Soong (android_app_import) with preprocessed: true,
  which installs it byte for byte. Anything else re-packs it, and for an app
  targeting SDK 30+ that breaks its v2/v3 signature. Keeping the authors'
  signature is also what lets their own later releases install over it.
- Apps built with extractNativeLibs=true keep their JNI libraries compressed
  in the APK. An app bundled in the image never has them extracted by the
  package manager (PackageAbiHelperImpl.shouldExtractLibs), and cannot load
  compressed ones from the APK, so each library is extracted here and
  installed into <partition>/app/<name>/lib/<isa>/, where the package manager
  looks for a bundled app's libraries. Soong has no module type that installs
  there, so these are Make prebuilts (Android.mk).
- skip_preprocessed_apk_checks: true is then needed, because Soong's check for
  preprocessed APKs refuses compressed JNI libraries: correct for libraries
  loaded from the APK, not for ones installed beside it.

    SRC=/srv/lineage DLCACHE=/dlcache python3 prebuilt_apps.py
"""

import hashlib
import json
import os
import shutil
import sys
import tempfile
import urllib.request
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK = os.path.join(HERE, "PrebuiltApps", "apps.json")
SRC = os.environ.get("SRC", "/srv/lineage")
CACHE = os.path.join(os.environ.get("DLCACHE", "/dlcache"), "prebuilt-apps")
OUT = os.path.join(SRC, "vendor", "jetson-tv", "PrebuiltApps")
ABI = "arm64-v8a"   # the device's primary ABI
ISA = "arm64"       # the directory name the package manager uses for it


def note(msg):
    print(f"    [apps] {msg}")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(url, want, dest):
    """dest, fetched if missing or wrong; fails loudly on a digest mismatch."""
    if os.path.exists(dest) and sha256(dest) == want:
        return dest
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    note(f"downloading {url}")
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(dest))
    os.close(fd)
    try:
        with urllib.request.urlopen(url, timeout=120) as r, open(tmp, "wb") as f:
            shutil.copyfileobj(r, f)
        got = sha256(tmp)
        if got != want:
            sys.exit(f"prebuilt_apps: {url}\n  sha256 {got}\n  pinned {want}\n"
                     "  refusing it: update apps.json deliberately if the release changed")
        os.chmod(tmp, 0o644)  # mkstemp makes it 0600
        os.replace(tmp, dest)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
    return dest


def write_if_changed(path, text):
    if os.path.exists(path) and open(path).read() == text:
        return False
    with open(path, "w") as f:
        f.write(text)
    return True


def copy_if_changed(src, dst):
    if os.path.exists(dst) and sha256(dst) == sha256(src):
        return False
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)
    return True


def main():
    apps = json.load(open(LOCK))["apps"]
    os.makedirs(OUT, exist_ok=True)
    bp = ["// Generated by scripts/in-container/prebuilt_apps.py from apps.json. Do not edit.\n"]
    mk = ["# Generated by scripts/in-container/prebuilt_apps.py from apps.json. Do not edit.",
          "LOCAL_PATH := $(call my-dir)", ""]
    packages = []
    keep = set()
    for app in apps:
        name, ver = app["name"], app["version"]
        keep.add(name)
        apk = fetch(app["apk"]["url"], app["apk"]["sha256"],
                    os.path.join(CACHE, f"{name}-{ver}.apk"))
        lic = fetch(app["license"]["url"], app["license"]["sha256"],
                    os.path.join(CACHE, f"{name}-{ver}.LICENSE"))
        d = os.path.join(OUT, name)
        changed = copy_if_changed(apk, os.path.join(d, f"{name}.apk"))
        changed |= copy_if_changed(lic, os.path.join(d, "LICENSE"))

        # The JNI libraries for the device's ABI, extracted beside the APK.
        libdir = os.path.join(d, "lib", ISA)
        with zipfile.ZipFile(apk) as z:
            libs = sorted(n for n in z.namelist()
                          if n.startswith(f"lib/{ABI}/") and n.endswith(".so"))
            wanted = {os.path.basename(n) for n in libs}
            if os.path.isdir(libdir):
                for stale in set(os.listdir(libdir)) - wanted:
                    os.unlink(os.path.join(libdir, stale))
                    changed = True
            os.makedirs(libdir, exist_ok=True)
            for n in libs:
                target = os.path.join(libdir, os.path.basename(n))
                data = z.read(n)
                if not os.path.exists(target) or open(target, "rb").read() != data:
                    with open(target, "wb") as f:
                        f.write(data)
                    changed = True

        # Soong checks these against the manifest's <uses-library> tags.
        libs = ""
        for key in ("uses_libs", "optional_uses_libs"):
            if app.get(key):
                libs += f"\n    {key}: [" + ", ".join(f'"{l}"' for l in app[key]) + "],"
        bp.append(f'''license {{
    name: "{name}_license",
    visibility: [":__subpackages__"],
    license_kinds: ["{app["license"]["kind"]}"],
    license_text: ["{name}/LICENSE"],
}}

// {name} {ver} ({app["package"]}). Source: {app["source"]}
android_app_import {{
    name: "{name}",
    apk: "{name}/{name}.apk",
    preprocessed: true,
    skip_preprocessed_apk_checks: true,
    product_specific: true,
    licenses: ["{name}_license"],{libs}
}}
''')
        packages.append(name)
        for so in sorted(wanted):
            mod = f"{name}_jni_{so[:-3]}"
            packages.append(mod)
            mk += [
                f"# {name}'s {so}, extracted from its APK: see prebuilt_apps.py.",
                "include $(CLEAR_VARS)",
                f"LOCAL_MODULE := {mod}",
                "LOCAL_MODULE_CLASS := ETC",
                f"LOCAL_MODULE_STEM := {so}",
                f"LOCAL_SRC_FILES := {name}/lib/{ISA}/{so}",
                f"LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/app/{name}/lib/{ISA}",
                f"LOCAL_LICENSE_KINDS := {app['license']['kind']}",
                "LOCAL_LICENSE_CONDITIONS := restricted",
                f"LOCAL_NOTICE_FILE := $(LOCAL_PATH)/{name}/LICENSE",
                "include $(BUILD_PREBUILT)",
                "",
            ]
        note(f"{name} {ver}: {len(wanted)} JNI librar{'y' if len(wanted) == 1 else 'ies'}"
             f"{' (updated)' if changed else ', already current'}")

    for entry in os.listdir(OUT):
        p = os.path.join(OUT, entry)
        if os.path.isdir(p) and entry not in keep:
            shutil.rmtree(p)
            note(f"{entry} removed: no longer in apps.json")
    write_if_changed(os.path.join(OUT, "Android.bp"), "\n".join(bp))
    write_if_changed(os.path.join(OUT, "Android.mk"), "\n".join(mk))
    write_if_changed(os.path.join(OUT, "prebuilt-apps.mk"),
                     "# Generated by scripts/in-container/prebuilt_apps.py. Do not edit.\n"
                     "PRODUCT_PACKAGES += \\\n    " + " \\\n    ".join(packages) + "\n")


if __name__ == "__main__":
    main()
