#!/usr/bin/env python3
"""
Put the pinned wireless firmware (Firmware/firmware.json) into the tree.

The tree can drive radios it has no firmware for. Intel's Wireless-AC cards
are the case in point: iwlwifi is in the kernel source and names the 8265
explicitly, but no ucode ships, so the card binds and then fails to start.
This fetches each pinned file into the download cache, checks its sha256, and
stages it under vendor/jetson-tv/Firmware with a makefile that installs it to
/vendor/firmware, where the kernel's firmware loader looks.

Nothing binary is committed to this repo. Run by tree-local-changes.sh, so by
every build; a cache hit costs nothing and needs no network.

Pinned to a linux-firmware *tag*. The 4.9 kernel here asks for 8265 ucode API
22 to 26 by exact filename, and linux-firmware's main branch carries only 34
and 36 -- files this driver will never request. firmware.json says as much.

    SRC=/srv/lineage DLCACHE=/dlcache python3 prebuilt_firmware.py
"""

import hashlib
import json
import os
import shutil
import sys
import tempfile
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
LOCK = os.path.join(HERE, "Firmware", "firmware.json")
SRC = os.environ.get("SRC", "/srv/lineage")
CACHE = os.path.join(os.environ.get("DLCACHE", "/dlcache"), "firmware")
OUT = os.path.join(SRC, "vendor", "jetson-tv", "Firmware")


def note(msg):
    print(f"    [firmware] {msg}")


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def fetch(url, want, dest):
    """dest, fetched if missing or wrong; fails loudly on a digest mismatch."""
    if os.path.exists(dest) and sha256(dest) == want:
        return dest
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    note(f"downloading {os.path.basename(dest)}")
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(dest))
    os.close(fd)
    try:
        # kernel.org answers 403 to urllib's default user agent.
        req = urllib.request.Request(url, headers={"User-Agent": "jetson-tv/1.0"})
        with urllib.request.urlopen(req, timeout=180) as r, open(tmp, "wb") as f:
            shutil.copyfileobj(r, f)
        got = sha256(tmp)
        if got != want:
            sys.exit(f"prebuilt_firmware: {url}\n  sha256 {got}\n  pinned {want}\n"
                     "  refusing it: update firmware.json deliberately if it changed")
        os.chmod(tmp, 0o644)   # mkstemp makes it 0600
        os.replace(tmp, dest)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)
    return dest


def write_if_changed(path, text):
    if os.path.exists(path) and open(path).read() == text:
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(text)
    return True


def copy_if_changed(src, dst):
    if os.path.exists(dst) and sha256(dst) == sha256(src):
        return False
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    shutil.copyfile(src, dst)
    return True


def main():
    lock = json.load(open(LOCK))
    base = lock["source"].rstrip("/") + "/plain"
    tag = lock["tag"]
    os.makedirs(OUT, exist_ok=True)
    lines = [
        "# Generated by scripts/in-container/prebuilt_firmware.py from",
        "# Firmware/firmware.json. Do not edit.",
        f"# linux-firmware {tag}",
        "",
    ]
    changed = 0
    for f in lock["files"]:
        url = f"{base}/{f['path']}?h={tag}"
        cached = fetch(url, f["sha256"], os.path.join(CACHE, tag, f["name"]))
        rel = os.path.join(f["dest"], f["name"]) if f["dest"] else f["name"]
        if copy_if_changed(cached, os.path.join(OUT, rel)):
            changed += 1
        # PRODUCT_COPY_FILES, so it lands in /vendor/firmware where the
        # kernel's loader looks. One line per file, with why it is here.
        lines += [
            f"# {f['why']}",
            "PRODUCT_COPY_FILES += \\",
            f"    vendor/jetson-tv/Firmware/{rel}:"
            f"$(TARGET_COPY_OUT_VENDOR)/firmware/{rel}",
            "",
        ]
    write_if_changed(os.path.join(OUT, "firmware.mk"), "\n".join(lines))
    note(f"{len(lock['files'])} file(s) from linux-firmware {tag}"
         f"{f', {changed} updated' if changed else ', already current'}")


if __name__ == "__main__":
    main()
